require "models/bank"
require "models/transaction"
require "models/account"
require "models/transfers/base"
require "models/transfers/inter_bank"
require "models/transfers/intra_bank"
require "repositories/accounts"
require "repositories/transactions"
